OUTPUT_DIR: ./outputs/phys
DATA_ROOT: 'data/dynamics/w0_rpcin_0_t10_d256_lr2e4_mlw0003_p200n800a100/'
DATASET_ABS: 'PyPhys'
SOLVER:
  BASE_LR: 1.0e-3  # single GPU LR
  WEIGHT_DECAY: 0.0
  SCHEDULER: 'cosine'
  MAX_ITERS: 100000
  VAL_INTERVAL: 10000
  BATCH_SIZE: 64 # single GPU Batch Size
PCLS:
  ARCH: 'resnet18film'
